name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install QEMU (X86_64)
      run: sudo apt-get install qemu-system-x86_64
    - name: Install Target Architecture (ARM Processor)
      run: rustup target add thumbv7em-none-eabihf
    - name: Install Nightly Rust
      run: rustup override set nightly
    - name: Install Rust-Src
      run: rustup component add rust-src
    - name: Install LLVM-Tools-Preview
      run: rustup component add llvm-tools-preview
    - name: Install Bootimage
      run: cargo install bootimage
    - name: Build KERNEL IMAGE
      run: cd kernel; cargo bootimage --verbose
