name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: TargetA
      run: rustup target add thumbv7em-none-eabihf
    - name: Nightly
      run: rustup override set nightly
    - name: Src
      run: rustup component add rust-src
    - name: LLVM-Tools-Preview
      run: rustup component add llvm-tools-preview
    - name: Bootimage
      run: cargo install bootimage
    - name: Build
      run: cd kernel; cargo bootimage --verbose
