name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install QEMU (X86_64)
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        image: tonistiigi/binfmt:latest
        platforms: x86_64
    - name: Install Target Architecture (ARM Processor)
      run: rustup target add thumbv7em-none-eabihf
    - name: Install Nightly Rust
      run: rustup override set nightly
    - name: Install Rust-Src
      run: rustup component add rust-src
    - name: Install LLVM-Tools-Preview
      run: rustup component add llvm-tools-preview
    - name: Install Bootimage
      run: cargo install bootimage
    - name: Build KERNEL IMAGE
      run: cd kernel; cargo bootimage --verbose
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist-without-markdown
        path: /home/runner/work/rust_kernel/rust_kernel/kernel/target/x86_64-rust_kernel/debug/bootimage-rust_kernel.bin 
