name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: TargetA
      run: rustup target add thumbv7em-none-eabihf
    - name: Nightly
      run: rustup override set nightly
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
